### ISSUE TITLE
Setproctitle dependency 

### ISSUE THREAD

**Issue by thedod** [filerock/FileRock-Client#3]
Took me time to figure out I also needed to install `setproctitle`, because when I ran [the github version of] the client, it just exited without saying anything.

**Comment by marcodb** [comment]
By default the application doesn't write anything to the console, even if it's been started from there. There were several ways to understand what was happening:
a) to look in the debug log, which is a file whose location depends on the operating system - it's ~/.filerock/client.log on linux;
b) to run the application in developer mode, by adding the -d flag on the command line
c) to look in the readme file (it's in the root of the sources tree), which contains all the required dependencies.

Thank you for using FileRock!

**Comment by thedod** [comment]
My bad. When I saw

> The following are required only on Linux and Mac OS X

My eyes skipped the word "linux" :)
